### ISSUE TITLE
Which is the open source version

### ISSUE THREAD

**Issue by jamesagada** [HubbellCorp/SweetBlue#17]
1.     implementation "com.idevicesinc:sweetblue:4.0.0.5-SNAPSHOT" doesn't exist. So it seems this is not open source yet.
2. How does one get a working apices?

**Comment by ryanhubbell** [comment]
Don't use the SNAPSHOT version. SNAPSHOT versions are for testing, and are not guaranteed to work, or even exist.

**Comment by ryanhubbell** [comment]
I realize now that the docs had the wrong version in them. They have been updated to show the correct version, sorry about that.
